# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'strategy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QLabel

Product = None


class Ui_Dialog(object):
    def __init__(self, Dialog):
        self.setupUi(Dialog)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(945, 315)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(750, 100, 75, 51))
        self.pushButton.setObjectName("pushButton")

        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(70, 100, 651, 51))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_2.addWidget(self.textEdit)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        """
        ComboBox settings
        """
        self.comboBox.addItems(['None', 'Breaking', 'Call-back'])

        self.horizontalLayout_2.addWidget(self.comboBox)
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_2.addWidget(self.textEdit_2)
        self.textEdit_3 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout_2.addWidget(self.textEdit_3)
        self.textEdit_4 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_4.setObjectName("textEdit_4")
        self.horizontalLayout_2.addWidget(self.textEdit_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)

        """
        on click setting
        """
        self.pushbutton.clicked.connect(self.onclick_evaluate())

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Evaluate"))
        self.label.setText(_translate("Dialog", "Product"))
        self.label_2.setText(_translate("Dialog", "Strategy"))
        self.label_3.setText(_translate("Dialog", "In Price"))
        self.label_4.setText(_translate("Dialog", "Win"))
        self.label_5.setText(_translate("Dialog", "Loss"))
        self.label_6.setText(_translate("Dialog", "Ratio"))
        self.label_7.setText(_translate("Dialog", "Null"))

    def onClick_evaluate(self):
        # sender=self.sender()
        if self.textEdit.toPlainText():
            self.textEdit.setText('<font color=\"#FF0000\">Enter entirely.</font>')
        elif self.textEdit_2.toPlainText():
            self.textEdit_2.setText('<font color=\"#FF0000\">Enter entirely.</font>')
        elif self.textEdit_3.toPlainText():
            self.textEdit_3.setText('<font color=\"#FF0000\">Enter entirely.</font>')
        elif self.textEdit_4.toPlainText():
            self.textEdit_4.setText('<font color=\"#FF0000\">Enter entirely.</font>')
        elif self.comboBox.currentText() == 'None':
            self.open_dialog(label='Stop action.')
        else:
            global Product
            Product = self.textEdit.toPlainText()
            in_price = float(self.textEdit.toPlainText())
            win_price = float(self.textEdit.toPlainText())
            loss_price = float(self.textEdit.toPlainText())

            ratio = abs((win_price - in_price) / (loss_price - in_price))
            self.label_7.setText(str(ratio))

    def open_dialog(self, label=None, button=None):
        """

        :param label: string in label
        :param button: [button name, onClick function]
        :return:
        """
        dlg = QDialog()
        if label:
            lbl = QLabel()
            lbl.setText(label)
            lbl.move(50, 50)

        if button:
            pass

        dlg.setWindowTitle('Warning')
        dlg.setWindowModality(QtCore.Qt.ApplicationModal)
        dlg.exec_()
